version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"