std = "luau+mw"
exclude = [
  "modules/_legacy/**",
  "modules/shared/_imported/**",
  "*.d.lua",
  "*.d.luau",
  "modules/**/scw:*",
  "modules/**/w:*",
  "modules/**/runescape:*",
  "modules/**/utgw:*",
  "modules/**/i:*",
]

[lints]
multiple_statements = "allow"
empty_if = "allow"
unused_variable = "allow"
mixed_table = "allow"