const fs = require('fs');
const file_path = process.argv[2];

if (!file_path) process.exit(1);

const HEADER = [
  '-- DO NOT EDIT THIS FILE MANUALLY.',
  '',
  '-- This file was automatically minified and transpiled from Luau by DarkLua.',
  '-- The original source code was written in Luau, the below code is transpiled and compatible with Lua 5.1.5 and contains the necessary polyfills.',
  '',
  '-- Uploaded automatically via WikiWire. View the original source at our central code repository: https://github.com/obbywiki/modules',
  '-- ANY EDITS WILL LIKELY BE OVERWRITTEN. A copyright notice should be supplied at the bottom of this page.',
].join('\n');

const POLYFILL_MAP = {
  'table.find': 'table.find=table.find or function(t,v,i) for j=i or 1,#t do if t[j]==v then return j end end end',
  'table.clear': 'table.clear=table.clear or function(t) for k in pairs(t) do t[k]=nil end end',
  'table.create': 'table.create=table.create or function(n,v) local t={} for i=1,n do t[i]=v end return t end',

  'string.split': 'string.split=string.split or function(s,sep) return mw.text.split(s,sep,true) end'
};

try {
  let content = fs.readFileSync(file_path, 'utf8');

  // polyfill injections


  let injections = [];

  for (const [key, code] of Object.entries(POLYFILL_MAP)) {
    if (content.includes(key)) {
      injections.push(code);
    }
  }

  let output = HEADER + '\n\n';
  
  if (injections.length > 0) {
    output += injections.join(';') + ';\n';
  }
  
  output += content;

  fs.writeFileSync(file_path, output);

  console.log("::debug::File contents for", file_path, "after polyfills:", output);
  
  console.log(`Processed ${file_path} successfully. Around ${injections.length} polyfills injected.`);
} catch (err) {
  console.error(`Error processing ${file_path}:`, err);
  process.exit(1);
}