name: Luacheck
on:
  push:
    paths:
      - 'modules/**'
      - 'modules/*'
  pull_request:
    paths:
      - 'modules/**'
      - 'modules/*'

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Luacheck linter
        uses: lunarmodules/luacheck@v1