name: Luacheck
on:
  push:
    paths:
      - 'modules/**'
      - '.luacheckrc'
      - '.github/workflows/luacheck.yml'
  pull_request:
    paths:
      - 'modules/**'
      - '.luacheckrc'
      - '.github/workflows/luacheck.yml'

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Luacheck linter
        uses: lunarmodules/luacheck@v1
