name: Selene
on:
  push:
    paths:
      - 'modules/**'
      - 'selene.toml'
      - 'mw.yml'
      - 'aftman.toml'
      - '.github/workflows/selene.yml'
  pull_request:
    paths:
      - 'modules/**'
      - 'selene.toml'
      - 'mw.yml'
      - 'aftman.toml'
      - '.github/workflows/selene.yml'

jobs:
  selene:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.4.2
      - name: Lint with Selene
        run: selene modules --allow-warnings
