name: WikiWire

on:
  push:
    branches: [main]

jobs:
  wikiwire:
    runs-on: ubuntu-latest
    name: Sync files to production MediaWiki
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: obbywiki/wikiwire@5ce03ebc51e86f9b887df321bef796eef49a610e
        env:
            GITHUB_TOKEN: ${{ secrets.WIKIWIRE_GITHUB_TOKEN }}
        with:
          username: WikiWireBot@WikiWire
          password: ${{ secrets.WIKIWIRE_PASSWORD }}